### ISSUE TITLE
This is useless. Simple web app but too complicated to install.

### ISSUE THREAD

**Issue by ghost** [puikinsh/Adminator-admin-dashboard#280]
<h1>Bug report</h1>
<h1>Feature request</h1>
<h1>Support request</h1>
<h1>Documentation issue</h1>

# Current behavior

# Expected behavior 

# Environment
Platform: 
Browser: 

For building issues:
Node:           
NPM:

**Comment by wsajjadh** [comment]
I agree.

**Comment by jepperaskdk** [comment]
How is it "useless"? Maybe describe what isn't working for you.
This issue tracks whether the theme can be prebuilt if that's what you're missing:
https://github.com/puikinsh/Adminator-admin-dashboard/issues/145

It is made with modern technologies, so you can integrate it into your target framework and its build processes.
I'm using it with Angular for instance, and I can adapt the theme exactly as I like, using the source-files rather than the built CSS/JS files (which would be extremely difficult to alter).
