### ISSUE TITLE
I simply dowloaded bootstrap and opend index page. It is not loading any css file. Please help

### ISSUE THREAD

**Issue by rgrgadhvi6** [puikinsh/Adminator-admin-dashboard#79]
<h1>Bug report</h1>
<h1>Feature request</h1>
<h1>Support request</h1>
<h1>Documentation issue</h1>

# Current behavior

# Expected behavior 

# Environment
Platform: 
Browser: 

For building issues:
Node:           
NPM:

**Comment by krzysiekpiasecki** [comment]
You don't need install anything manually. Just build the application.

#### Installing & Local Development
Start by typing the following commands in your terminal in order to get **Adminator** full package on your machine and starting a local development server with live reload feature.

```
> git clone https://github.com/puikinsh/Adminator-admin-dashboard.git adminator
> cd adminator
> npm install
> npm run dev
```

If you don't have any further questions please close this ticket.

**Comment by rgrgadhvi6** [comment]
Hey mate,
I was thinking to use bootstrap directly in my computer. So, what I was
trying to do was to download the clone and edit the HTML files in it. I
don't have much knowledge for all that terminal and everything.
Please tell me how I can use the clone direct download and attach the css
and jabescripts.

Thanks
Rajesh

**Comment by Gopalkrishna69** [comment]
Please find the attached it may be useful for you ....
[Adminator.zip](https://github.com/puikinsh/Adminator-admin-dashboard/files/1914897/Adminator.zip)
